# TTS Configuration Settings
# This file contains configuration options for different TTS methods

# Default TTS method (used when not specified in stages.yaml)
default_tts_method: "xtts"

# Global TTS settings
use_emotion_in_tts: true

# Available TTS methods and their configurations
tts_methods:

  # F5-TTS Configuration
  f5:
    name: "F5-TTS"
    description: "Advanced TTS with voice cloning capabilities"
    enabled: true
    config:
      model_path: "models/f5-tts"
      device: "cuda"  # Options: "cpu", "cuda", "auto"
      voice_cloning: true
      emotion_support: false
      language_support: ["en", "ja", "zh", "ko", "es", "fr", "de"]

  # Edge-TTS Configuration
  edge_tts:
    name: "Edge TTS"
    description: "Microsoft Edge TTS with natural voices"
    enabled: true
    config:
      voice: "en-US-AriaNeural"  # Default voice
      rate: "+0%"  # Speech rate (-100% to +100%)
      volume: "+0%"  # Volume level (-100% to +100%)
      pitch: "+0Hz"  # Pitch adjustment (-50Hz to +50Hz)
      style: "general"  # Speaking style
      style_degree: 1.0  # Style intensity (0.01 to 2.0)
      language_support: ["en", "ja", "zh", "ko", "es", "fr", "de", "it", "pt", "ru", "ar", "hi"]

  # XTTS Configuration
  xtts:
    name: "Coqui XTTS-v2"
    description: "Multilingual TTS with voice cloning from reference audio"
    enabled: true
    config:
      model_name: "tts_models/multilingual/multi-dataset/xtts_v2"
      device: "cuda"  # or "cpu"
      speaker_wav_duration: 6  # seconds to use from ref
      language: "auto"  # infer from target_lang
      speed: 1.0  # Speed factor (1.0 = normal, max 2.0 = 2x speed)
      temperature: 0.7  # for variation/emotion
      emotion_support: true  # if optional stage active
      languages: ["en", "ja", "zh", "ko", "es", "fr", "de", "it", "pt", "ru", "ar", "hi"]

  # Orpheus-TTS Configuration
  orpheus:
    name: "Orpheus-TTS"
    description: "Advanced multilingual TTS with enhanced voice quality and emotion support"
    enabled: true
    config:
      model_type: "finetuned"  # Options: "finetuned", "pretrained", "multilingual"
      voice: "tara"  # Default voice name
      device: "cuda"  # Requires GPU
      emotion_tags: true  # Enable emotion tags in prompts
      temperature: 0.7  # Generation temperature for variation
      repetition_penalty: 1.1  # Repetition penalty
      language_support: ["en", "ja", "zh", "ko", "es", "fr", "de", "it", "pt", "ru"]

# Voice mapping for different speakers (optional)
# Maps speaker IDs to specific TTS voices
voice_mapping:
  SPEAKER_00: "en-US-AriaNeural"  # Default female voice
  SPEAKER_01: "en-US-GuyNeural"    # Default male voice
  # Add more speaker mappings as needed

# Quality settings
quality:
  sample_rate: 22050  # Target sample rate for audio
  bitrate: "128k"     # Target bitrate for compressed audio
  format: "wav"       # Output format (wav, mp3, etc.)

# Performance settings
performance:
  batch_size: 1       # Number of segments to process in parallel
  max_workers: 4      # Maximum number of concurrent TTS workers
  timeout: 300        # Timeout in seconds for TTS generation

# Reference audio settings
reference_audio:
  min_duration_minutes: 1  # Minimum duration in minutes for reference audio per speaker